// <auto-generated />
using System;
using ABreak.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ABreak.Infrastructure.Migrations
{
    [DbContext(typeof(ABreakDbContext))]
    [Migration("20251112034315_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ABreak.Domain.Entities.ConfiguracaoPausa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("HorarioFimTrabalho")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("HorarioInicioTrabalho")
                        .HasColumnType("TEXT");

                    b.Property<int>("IntervaloMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotificacaoAtiva")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoPausaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TipoPausaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ConfiguracoesPausa");
                });

            modelBuilder.Entity("ABreak.Domain.Entities.Notificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHoraNotificacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataHoraVisualizacao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PausaRealizada")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoPausaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Visualizada")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TipoPausaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notificacoes");
                });

            modelBuilder.Entity("ABreak.Domain.Entities.Pausa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completada")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataHoraFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoPausaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TipoPausaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pausas");
                });

            modelBuilder.Entity("ABreak.Domain.Entities.TipoPausa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("DuracaoRecomendadaMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TiposPausa");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Descricao = "Exercícios de alongamento",
                            DuracaoRecomendadaMinutos = 5,
                            Icone = "🧘",
                            Nome = "Alongamento"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Descricao = "Beber água",
                            DuracaoRecomendadaMinutos = 2,
                            Icone = "💧",
                            Nome = "Hidratação"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Descricao = "Descansar os olhos",
                            DuracaoRecomendadaMinutos = 3,
                            Icone = "👁️",
                            Nome = "Descanso Visual"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Descricao = "Caminhar um pouco",
                            DuracaoRecomendadaMinutos = 10,
                            Icone = "🚶",
                            Nome = "Caminhada"
                        });
                });

            modelBuilder.Entity("ABreak.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ABreak.Domain.Entities.ConfiguracaoPausa", b =>
                {
                    b.HasOne("ABreak.Domain.Entities.TipoPausa", "TipoPausa")
                        .WithMany("Configuracoes")
                        .HasForeignKey("TipoPausaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ABreak.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Configuracoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoPausa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ABreak.Domain.Entities.Notificacao", b =>
                {
                    b.HasOne("ABreak.Domain.Entities.TipoPausa", "TipoPausa")
                        .WithMany()
                        .HasForeignKey("TipoPausaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ABreak.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoPausa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ABreak.Domain.Entities.Pausa", b =>
                {
                    b.HasOne("ABreak.Domain.Entities.TipoPausa", "TipoPausa")
                        .WithMany("Pausas")
                        .HasForeignKey("TipoPausaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ABreak.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Pausas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoPausa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ABreak.Domain.Entities.TipoPausa", b =>
                {
                    b.Navigation("Configuracoes");

                    b.Navigation("Pausas");
                });

            modelBuilder.Entity("ABreak.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Configuracoes");

                    b.Navigation("Pausas");
                });
#pragma warning restore 612, 618
        }
    }
}
